### PR TITLE
Change from multiple route files to a single file

### PR DESCRIPTION
**Pull request by tamorim**
This PR implements the following:
- From `render/routes/*.json` and `render/settings/routes/*.json` to `render/routes.json`
- A little bit of code reorganization 
- Tests for the routes file generation

### CODE REVIEW

**Comment by brenoc** [comment]
I thought this was deprecated. If not, LGTM

**Comment by brenoc** [comment]
Also, missing tests

**Comment by brenoc** [comment]
Weird that the tests are actually passing lol

**Comment by brenoc** [comment]
Deleted my last comment. The tests are not testing for routes.

**Comment by tamorim** [comment]
@brenoc Now with tests! :smiley:

**Comment by brenoc** [comment]
AWESOME

**Pull request merged**
